// Writes supabase/seed/products.sql from the storefront catalogue
// (src/lib/data/products.json), so the database's product list matches the
// site. Run with `npm run db:products`, then run the file in the Supabase SQL
// editor (or `supabase db push` / psql). Safe to run again: it upserts by slug.
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url);
const products = JSON.parse(readFileSync(new URL("src/lib/data/products.json", root), "utf8"));
const brandsSource = readFileSync(new URL("src/lib/data/brands.ts", root), "utf8");
const brandNames = Object.fromEntries(
  [...brandsSource.matchAll(/slug:\s*"([^"]+)",\s*\n\s*name:\s*"([^"]+)"/g)].map((m) => [m[1], m[2]]),
);

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replaceAll("'", "''")}'`);

const rows = products.map((p) => {
  const brand = brandNames[p.brand] ?? p.brand;
  return `  (${[
    q(p.slug),
    q(`${brand} ${p.model}`),
    q(brand),
    q(p.model),
    q(p.reference ?? ""),
    q(p.description ?? ""),
    p.price === null ? "null" : Number(p.price).toFixed(2),
    q(p.currency),
    q(p.front ?? p.images?.[0] ?? null),
    p.availability === "Stokta" ? 1 : 0,
  ].join(", ")})`;
});

const sql = `-- Generated by scripts/products-seed.mjs from src/lib/data/products.json. Do not edit by hand.
insert into public.products (slug, name, brand, model, reference, description, price, currency, image, stock)
values
${rows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name,
  brand = excluded.brand,
  model = excluded.model,
  reference = excluded.reference,
  description = excluded.description,
  price = excluded.price,
  currency = excluded.currency,
  image = excluded.image,
  stock = excluded.stock,
  is_active = true;

-- Watches no longer in the catalogue stay for old orders and favourites but leave the shop.
update public.products set is_active = false
 where slug not in (${products.map((p) => q(p.slug)).join(", ")});
`;

writeFileSync(new URL("supabase/seed/products.sql", root), sql);
console.log(`supabase/seed/products.sql: ${products.length} products`);
